### ISSUE TITLE
Cannot import proxyquire

### ISSUE THREAD

**Issue by msieurtoph** [theKashey/proxyquire-webpack-alias#1]
Hi,

It seems you module is not working.

I am trying to use it and get : 

```
ERROR in xxx/node_modules/proxyquire-webpack-alias/proxyquire.d.ts (7,42): Cannot find name 'Proxyquire'.

ERROR in xxxxx (1,10): Module ''proxyquire-webpack-alias'' has no exported member 'proxyquire'.

ERROR in xxxxx (1,10): Module ''proxyquire-webpack-alias'' has no exported member 'proxyquire'.
```
As I simply did : 

```
npm i proxyquire-webpack-alias --save-dev
```

and just added this line (and no more yet) at the top of one of my specfiles :

```
import { proxyquire } from 'proxyquire-webpack-alias';
```

For the record, I am using angular-cli.
It's too bad, your module seemed promising...

**Comment by theKashey** [comment]
My bad :( I did not check how proxyquire-webpack-alias proxies typedef from proxyquire.
Will fix it asap.

**Comment by theKashey** [comment]
PS: Hooray! Issue #1

**Comment by theKashey** [comment]
@msieurtoph  - resolved. Just bump version.

**Comment by msieurtoph** [comment]
Still get the pb but with different errors : 

```
ERROR in xxxx/node_modules/proxyquire-webpack-alias/proxyquire.d.ts (15,5): Exports and export assignments are not permitted in module augmentations.

ERROR in xxxxxxx/xxxx.component.spec.ts (1,10): Module '"xxxxxx/node_modules/proxyquire-webpack-alias/proxyquire"' has no exported member 'proxyquire'.

ERROR in xxxxxxx/xxxx.component.spec.ts (1,10): Module '"xxxxxx/node_modules/proxyquire-webpack-alias/proxyquire"' has no exported member 'proxyquire'.
```

If it can help : when importing from 'proxyquire-webpack-alias', my IDE only detects the interface 'WebpackAliasProxyquire' as "importable" content.

**Comment by theKashey** [comment]
@msieurtoph - use `import proxyquire from 'proxyquire-webpack-alias';`

**Comment by msieurtoph** [comment]
Here we go. 
Thanks for spending time over my usecase.

Now it imports ```proxyquire``` ... but I cannot achieve what I want to do.

I want to proxyquire the ```saveAs``` exported function of the the third-library dependency ```file-saver``` of my component ```my-component```, and I want to mock this function with a noop one (```() => {}```)
Maybe I did not get how your module works (or maybe what it really does ).
Is it supposed to do the job or am I wrong about everything ? 

Here is the code in my spec file : 

```
import proxyquire from 'proxyquire-webpack-alias';
proxyquire
    .anyProxyquireCall()
    .load('./my-component', {'file-saver': {saveAs: () => {}} });
...
```

And here are the errors (and warnings) I get.

```
WARNING in ./~/proxyquire-2/lib/proxyquire.js
require.extensions is not supported by webpack. Use a loader instead.
 @ ./~/proxyquire-webpack-alias/lib/index.js 10:18-56
 @ ./xxxxxxx/my-component.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

WARNING in ./~/proxyquire-2/lib/proxyquire.js
require.extensions is not supported by webpack. Use a loader instead.
 @ ./~/proxyquire-webpack-alias/lib/index.js 10:18-56
 @ ./xxxxxxx/my-component.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

WARNING in ./~/proxyquire-2/lib/proxyquire.js
require.extensions is not supported by webpack. Use a loader instead.
 @ ./~/proxyquire-webpack-alias/lib/index.js 10:18-56
 @ ./xxxxxxx/my-component.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

WARNING in ./~/proxyquire-2/lib/proxyquire.js
require.extensions is not supported by webpack. Use a loader instead.
 @ ./~/proxyquire-webpack-alias/lib/index.js 10:18-56
 @ ./xxxxxxx/my-component.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

WARNING in ./~/proxyquire-2/lib/proxyquire.js
require.extensions is not supported by webpack. Use a loader instead.
 @ ./~/proxyquire-webpack-alias/lib/index.js 10:18-56
 @ ./xxxxxxx/my-component.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

WARNING in ./~/proxyquire-webpack-alias/lib/aliases.js
71:15-32 Critical dependency: the request of a dependency is an expression

ERROR in xxxxxxx/my-component.spec.ts (4,6): Property 'anyProxyquireCall' does not exist on type 'WebpackAliasProxyquire'.

ERROR in xxxxxxx/my-component.spec.ts (4,6): Property 'anyProxyquireCall' does not exist on type 'WebpackAliasProxyquire'.

ERROR in xxxxxxx\node_modules\proxyquire-2\lib'
Module not found: Error: Can't resolve 'module' in 'xxxxxx\node_modules\proxyquire-2\lib'
 @ ./~/proxyquire-2/lib/proxyquire.js 5:13-30
 @ ./~/proxyquire-webpack-alias/lib/index.js
 @ ./xxxxxxx/my-component.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts
```
 
It seems that ```anyProxyquireCall``` is not reconized. (I tried to comment this line, but it does not change the other errors).

Thanks again for your time.

**Comment by theKashey** [comment]
So, first of all, you should not use webpack for testing.

Second - proxyquire(and 99% of other libraries) will not work with webpack at all. You have to use inject loader or rewire-webpack.

Third - 
```js
proxyquire
    .anyProxyquireCall() <-- this is not 'anyProxyquireCall' - this is *any* method from proxyquire
    .load('./my-component', {'file-saver': {saveAs: () => {}} });
```
So, try to write
```js
proxyquire
  .noUnusedStubs()
  .noPreserveCache()
  .onlyForProjectFiles();
  .load('./my-component', {'file-saver': {saveAs: () => {}} });
```

**Comment by msieurtoph** [comment]
I still get the same errors (except the anyProxyquireCall error) using your last lines.

And concerning testing with webpack, I am using angular-cli (from the angular team) and it generates spec files this way, so I supposed it is a good practice for angular.

Excuse my misunderstanding but you said that proxyquire will not work with webpack at all ... so what is the purpose of your module proxyquire-webpack-alias ? I do not get it. I thought it was specially to make proxyquire work with webpack ...

I will have a look to rewire-webpack ... but the readme is so short ... :(

Tkx

**Comment by theKashey** [comment]
A `keyword` here is not webpack, but `webpack-alias`.
Proxyquire was created for Node.js environment, not for karma/angular tests. 
The difference is quite simple - in case of webpack application will run in browser, in absolutely different environment.
All current-workable mocking libraries for webpack are doing their work during compilation stage. Not in runtime. :( So - only babel-plugins or webpack-loaders will work, not any `normal` mock.

May be it is a good time to "fix" it.
Until then - the best way to mock something in Angular is to use DI.

**Comment by theKashey** [comment]
@msieurtoph - you can try [rewiremock](https://github.com/theKashey/rewiremock). It supports proxyquire API, but can work inside webpack.
